#!/bin/sh -e

# VBoxAdm Common postrm
# Dominik Schulz <dominik.schulz@gauner.org>

case "$1" in
  remove)
    ;;
  upgrade)
    ;;
  purge)
    rm -rf /etc/vboxadm
    userdel vboxadm >/dev/null 2>&1 || true
    groupdel vboxadm >/dev/null 2>&1 || true
    ;;
  failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
#DEBHELPER#
